name: EmotICONS
main: KL\EI
version: 1.0
api: [3.0.7, 3.0.6, 3.1.0, 4.0.0, 4.0.1]
author: CodeBreaker

commands:
  \:
    description: Open the EmotICONS menu
  ei:
    description: Open the EmotICONS menu
