name: CosmetixUI
main: KL\CI
version: 1.3
api: [3.0.7, 3.0.6, 3.1.0, 4.0.0, 4.0.1]
author: CodeBreaker

commands:
  servercosmetics:
    description: Open the CosmetixUI (/servercosmetics | /cui | /++)
  cui:
    description: Open the CosmetixUI (/servercosmetics | /cui | /++)
  ++:
    description: Open the CosmetixUI (/servercosmetics | /cui | /++)